#ifndef GGGGT_NATIVE_DETECT_CTX_H
#define GGGGT_NATIVE_DETECT_CTX_H

#define GGGGT_SUPP_CTX_SWITCH_X86	1
#define GGGGT_SUPP_CTX_SWITCH_X86_64	2

#if defined(__GNUC__)
#if defined(__x86_64__)
#define GGGGT_SUPP_CTX_SWITCH GGGGT_SUPP_CTX_SWITCH_X86_64
#elif defined(__i386__)
#define GGGGT_SUPP_CTX_SWITCH GGGGT_SUPP_CTX_SWITCH_X86
#endif
#endif

#ifndef GGGGT_SUPP_CTX_SWITCH
#define GGGGT_SUPP_CTX_SWITCH 0
#endif

#endif
